### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by denyskolesnikov** [richard-muvirimi/android-timezone-picker#1]
Red imports

import com.android.timezonepicker.TimeZoneInfo
import com.android.timezonepicker.TimeZonePickerDialog

**Comment by richard-muvirimi** [comment]
Thank you will check it out and update

**Comment by richard-muvirimi** [comment]
@denyskolesnikov  This is now fixed, had been working on having Gradle pull in the required files i.e the base library and the timezone files
