### ISSUE TITLE
Double search fields on country search

### ISSUE THREAD

**Issue by bschick** [richard-muvirimi/android-timezone-picker#2]
Country selection is showing two overlapping search fields. Without input focus it look like this (hints overlapping):

<img width="263" alt="Screenshot 2023-04-24 at 11 12 26 PM" src="https://user-images.githubusercontent.com/238462/234189766-b8a4049c-780f-46ac-9378-f36076ad6547.png">

With input focus is looks like this:

<img width="259" alt="Screenshot 2023-04-24 at 11 14 25 PM" src="https://user-images.githubusercontent.com/238462/234189948-feca9c53-3742-44f8-9182-faa0fdbd7670.png">

Same results on:
Emulator: Pixel 3a API 33 in latest Android Studio
Physical: Samsung S21 Ultra API 33 (Android 13)

**Comment by richard-muvirimi** [comment]
What theme are you using, you may try to use the same as in the sample folder

**Comment by bschick** [comment]
I copied the theme from the sample app and the results are largely the same. Layout is a bit different, but still have the search fields doubled:

<img width="298" alt="Screenshot 2023-04-25 at 11 31 09 AM" src="https://user-images.githubusercontent.com/238462/234379727-c9d286f1-e852-471a-819d-d7d916141d2e.png">

The dialog is launched from an activity derived from AppCompatActivity with this code:

```
        Bundle args = new Bundle();
        args.putLong(
            TimeZonePickerDialog.BUNDLE_START_TIME_MILLIS,
            ZonedDateTime.now().toEpochSecond() * 1000
        );
        args.putString(
            TimeZonePickerDialog.BUNDLE_TIME_ZONE,
            ZonedDateTime.now().getZone().getId()
        );

        TimeZonePickerDialog timeZonePickerDialog = new TimeZonePickerDialog();
        timeZonePickerDialog.setArguments(args);
        timeZonePickerDialog.setOnTimeZoneSetListener(onTimeZoneSet);
        FragmentManager fm = getFragmentManager();
        timeZonePickerDialog.show(fm, TimeZonePickerDialog.TAG);
```

**Comment by richard-muvirimi** [comment]
I am not sure why it could be duplicating the hints as well as the search icon, make sure it is importing from the correct package as in the sample app
```kotlin
import com.tyganeutronics.timezonepicker.*
```
as the base library does not use app compact views and uses a Holo theme

If this is not the issue, just like it's done in the library folder, you can override the library Views with your own Views, make sure you also override the classes so that you use the correct views. Let me know if you still face the same issue after.

**Comment by bschick** [comment]
I have followed the steps in the README which creates a new TimeZonePickerDialog() instance. That class is not present in com.tyganeutronics.timezonepicker so Android studio auto imported com.android.timezonepicker.TimeZonePickerDialog. 

When I switch to create com.tyganeutronics.timezonepicker.TimeZonePickerBaseFragment instead (which is derived from TimeZonePickerDialog) the double search goes away.

Still a few other problems, but I'll build the sample app a test them there before opening tickets.

**Comment by richard-muvirimi** [comment]
You are correct, the example in the README is outdated, will adjust it to reflect the same as the ones in the sample folder

**Comment by richard-muvirimi** [comment]
Since there hasn't been any activity for more than 7 days, will be closing this issue. Feel free to reopen or create another if the issue persists.
